sudo: required
language: genric
services:
  - docker

before_install:
  - docker build -t bhavani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bhavani/docker-react npm run test
